# Generated by Django 4.1.3 on 2023-02-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=' ', max_length=35)),
                ('middleName', models.CharField(default=' ', max_length=35)),
                ('lastName', models.CharField(default=' ', max_length=35)),
                ('EducationsLiences', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to='images')),
                ('phoneNum', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('idNum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idNum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(default=' ', max_length=35)),
                ('middleName', models.CharField(default=' ', max_length=35)),
                ('lastName', models.CharField(default=' ', max_length=35)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='images')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phoneNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(default=' ', max_length=35)),
                ('middleName', models.CharField(default=' ', max_length=35)),
                ('lastName', models.CharField(default=' ', max_length=35)),
                ('account_type', models.CharField(max_length=10)),
                ('age', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('WhatBefor', models.CharField(max_length=255)),
                ('WhatAfter', models.CharField(max_length=255)),
                ('WhatToDo', models.CharField(max_length=255)),
                ('Symptoms', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=30)),
                ('Centers', models.CharField(default='h', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsAvailablesAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfAppoiment', models.DateField(blank=True, null=True)),
                ('Hosbital', models.CharField(max_length=30)),
                ('privateClinical', models.CharField(max_length=255)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('Online', models.BooleanField()),
                ('location', models.CharField(max_length=30)),
                ('DoctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='BookedAppoiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('DateANDtime', models.DateTimeField(blank=True, null=True)),
                ('PatientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctor.patient')),
                ('doctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctor.doctor')),
            ],
        ),
    ]
