# Generated by Django 4.1.3 on 2023-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Khartoum', models.CharField(max_length=255)),
                ('Bahri', models.CharField(max_length=255)),
                ('Omdurman', models.CharField(max_length=255)),
            ],
        ),
    ]
